server:
  port: 8080
  servlet:
    context-path: /reviewer

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/reviewer
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop